import type { Metadata } from 'next';
import { Playfair, Roboto } from 'next/font/google';
import './tailwind.css';

// const geistSans = Geist({
//     variable: '--font-geist-sans',
//     subsets: ['latin'],
// });

const roboto = Roboto({
    variable: '--font-roboto',
    weight: ['400', '700'],
});

const playfair = Playfair({
    variable: '--font-playfair',
    weight: ['400', '700'],
});
export const metadata: Metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
            <body
                className={`${playfair.variable} ${roboto.variable} antialiased`}>
                {children}
                <p className="bg-secondary">
                    Lorem ipsum dolor sit amet consectetur,
                    adipisicing elit. Reprehenderit aliquid,
                    sequi explicabo recusandae rem deserunt
                    dolor quas ad magni quo fugit tempora
                    doloremque, veniam numquam, laborum sed!
                    Amet, nostrum voluptatum.
                </p>
            </body>
        </html>
    );
}
